// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi8_CarsApp.Data;

#nullable disable

namespace WebApi8_CarsApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240813141648_AddSeedFabricante")]
    partial class AddSeedFabricante
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi8_CarsApp.Models.CarModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("FabricanteId")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoVeiculoId")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FabricanteId");

                    b.HasIndex("TipoVeiculoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("WebApi8_CarsApp.Models.CarTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipos");
                });

            modelBuilder.Entity("WebApi8_CarsApp.Models.MakerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fabricantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Aston Martin"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Audi"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "BMW"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "BYD"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "CAOA Chery"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Chevrolet"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Citroën"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Effa"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Ferrari"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Fiat"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Ford"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Foton"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "GWM"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Honda"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Hyundai"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Iveco"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "JAC"
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Jaguar"
                        },
                        new
                        {
                            Id = 19,
                            Nome = "Jeep"
                        },
                        new
                        {
                            Id = 20,
                            Nome = "Kia"
                        },
                        new
                        {
                            Id = 21,
                            Nome = "Lamborghini"
                        },
                        new
                        {
                            Id = 22,
                            Nome = "Land Rover"
                        },
                        new
                        {
                            Id = 23,
                            Nome = "Lexus"
                        },
                        new
                        {
                            Id = 24,
                            Nome = "Maserati"
                        },
                        new
                        {
                            Id = 25,
                            Nome = "McLaren"
                        },
                        new
                        {
                            Id = 26,
                            Nome = "Mercedes-AMG"
                        },
                        new
                        {
                            Id = 27,
                            Nome = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 28,
                            Nome = "Mini"
                        },
                        new
                        {
                            Id = 29,
                            Nome = "Mitsubishi"
                        },
                        new
                        {
                            Id = 30,
                            Nome = "Neta"
                        },
                        new
                        {
                            Id = 31,
                            Nome = "Nissan"
                        },
                        new
                        {
                            Id = 32,
                            Nome = "Peugeot"
                        },
                        new
                        {
                            Id = 33,
                            Nome = "Porsche"
                        },
                        new
                        {
                            Id = 34,
                            Nome = "RAM"
                        },
                        new
                        {
                            Id = 35,
                            Nome = "Renault"
                        },
                        new
                        {
                            Id = 36,
                            Nome = "Rolls-Royce"
                        },
                        new
                        {
                            Id = 37,
                            Nome = "Seres"
                        },
                        new
                        {
                            Id = 38,
                            Nome = "Subaru"
                        },
                        new
                        {
                            Id = 39,
                            Nome = "Suzuki"
                        },
                        new
                        {
                            Id = 40,
                            Nome = "Toyota"
                        },
                        new
                        {
                            Id = 41,
                            Nome = "Volkswagen"
                        },
                        new
                        {
                            Id = 42,
                            Nome = "Volvo"
                        });
                });

            modelBuilder.Entity("WebApi8_CarsApp.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("WebApi8_CarsApp.Models.CarModel", b =>
                {
                    b.HasOne("WebApi8_CarsApp.Models.MakerModel", "Fabricante")
                        .WithMany("Carros")
                        .HasForeignKey("FabricanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi8_CarsApp.Models.CarTypeModel", "TipoVeiculo")
                        .WithMany("Carros")
                        .HasForeignKey("TipoVeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi8_CarsApp.Models.UserModel", "Usuario")
                        .WithMany("Carros")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fabricante");

                    b.Navigation("TipoVeiculo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApi8_CarsApp.Models.CarTypeModel", b =>
                {
                    b.Navigation("Carros");
                });

            modelBuilder.Entity("WebApi8_CarsApp.Models.MakerModel", b =>
                {
                    b.Navigation("Carros");
                });

            modelBuilder.Entity("WebApi8_CarsApp.Models.UserModel", b =>
                {
                    b.Navigation("Carros");
                });
#pragma warning restore 612, 618
        }
    }
}
